// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/api.proto
// </auto-generated>
// Original file comments:
//
// Copyright (C) 2017 Dgraph Labs, Inc. and Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Style guide for Protocol Buffer 3.
// Use CamelCase (with an initial capital) for message names – for example,
// SongServerRequest. Use underscore_separated_names for field names – for
// example, song_name.
//
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace DGraphSample.Api {
  /// <summary>
  /// Graph response.
  /// </summary>
  public static partial class Dgraph
  {
    static readonly string __ServiceName = "api.Dgraph";

    static readonly grpc::Marshaller<DGraphSample.Api.LoginRequest> __Marshaller_api_LoginRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), DGraphSample.Api.LoginRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<DGraphSample.Api.Response> __Marshaller_api_Response = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), DGraphSample.Api.Response.Parser.ParseFrom);
    static readonly grpc::Marshaller<DGraphSample.Api.Request> __Marshaller_api_Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), DGraphSample.Api.Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<DGraphSample.Api.Mutation> __Marshaller_api_Mutation = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), DGraphSample.Api.Mutation.Parser.ParseFrom);
    static readonly grpc::Marshaller<DGraphSample.Api.Assigned> __Marshaller_api_Assigned = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), DGraphSample.Api.Assigned.Parser.ParseFrom);
    static readonly grpc::Marshaller<DGraphSample.Api.Operation> __Marshaller_api_Operation = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), DGraphSample.Api.Operation.Parser.ParseFrom);
    static readonly grpc::Marshaller<DGraphSample.Api.Payload> __Marshaller_api_Payload = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), DGraphSample.Api.Payload.Parser.ParseFrom);
    static readonly grpc::Marshaller<DGraphSample.Api.TxnContext> __Marshaller_api_TxnContext = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), DGraphSample.Api.TxnContext.Parser.ParseFrom);
    static readonly grpc::Marshaller<DGraphSample.Api.Check> __Marshaller_api_Check = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), DGraphSample.Api.Check.Parser.ParseFrom);
    static readonly grpc::Marshaller<DGraphSample.Api.Version> __Marshaller_api_Version = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), DGraphSample.Api.Version.Parser.ParseFrom);

    static readonly grpc::Method<DGraphSample.Api.LoginRequest, DGraphSample.Api.Response> __Method_Login = new grpc::Method<DGraphSample.Api.LoginRequest, DGraphSample.Api.Response>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Login",
        __Marshaller_api_LoginRequest,
        __Marshaller_api_Response);

    static readonly grpc::Method<DGraphSample.Api.Request, DGraphSample.Api.Response> __Method_Query = new grpc::Method<DGraphSample.Api.Request, DGraphSample.Api.Response>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Query",
        __Marshaller_api_Request,
        __Marshaller_api_Response);

    static readonly grpc::Method<DGraphSample.Api.Mutation, DGraphSample.Api.Assigned> __Method_Mutate = new grpc::Method<DGraphSample.Api.Mutation, DGraphSample.Api.Assigned>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Mutate",
        __Marshaller_api_Mutation,
        __Marshaller_api_Assigned);

    static readonly grpc::Method<DGraphSample.Api.Operation, DGraphSample.Api.Payload> __Method_Alter = new grpc::Method<DGraphSample.Api.Operation, DGraphSample.Api.Payload>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Alter",
        __Marshaller_api_Operation,
        __Marshaller_api_Payload);

    static readonly grpc::Method<DGraphSample.Api.TxnContext, DGraphSample.Api.TxnContext> __Method_CommitOrAbort = new grpc::Method<DGraphSample.Api.TxnContext, DGraphSample.Api.TxnContext>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CommitOrAbort",
        __Marshaller_api_TxnContext,
        __Marshaller_api_TxnContext);

    static readonly grpc::Method<DGraphSample.Api.Check, DGraphSample.Api.Version> __Method_CheckVersion = new grpc::Method<DGraphSample.Api.Check, DGraphSample.Api.Version>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CheckVersion",
        __Marshaller_api_Check,
        __Marshaller_api_Version);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return DGraphSample.Api.ApiReflection.Descriptor.Services[0]; }
    }

    /// <summary>Lite client for Dgraph</summary>
    public partial class DgraphClient : grpc::LiteClientBase
    {
      /// <summary>Creates a new client for Dgraph that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public DgraphClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected DgraphClient() : base()
      {
      }

      public virtual DGraphSample.Api.Response Login(DGraphSample.Api.LoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Login(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual DGraphSample.Api.Response Login(DGraphSample.Api.LoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Login, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<DGraphSample.Api.Response> LoginAsync(DGraphSample.Api.LoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LoginAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<DGraphSample.Api.Response> LoginAsync(DGraphSample.Api.LoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Login, null, options, request);
      }
      public virtual DGraphSample.Api.Response Query(DGraphSample.Api.Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Query(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual DGraphSample.Api.Response Query(DGraphSample.Api.Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Query, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<DGraphSample.Api.Response> QueryAsync(DGraphSample.Api.Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QueryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<DGraphSample.Api.Response> QueryAsync(DGraphSample.Api.Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Query, null, options, request);
      }
      public virtual DGraphSample.Api.Assigned Mutate(DGraphSample.Api.Mutation request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Mutate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual DGraphSample.Api.Assigned Mutate(DGraphSample.Api.Mutation request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Mutate, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<DGraphSample.Api.Assigned> MutateAsync(DGraphSample.Api.Mutation request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MutateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<DGraphSample.Api.Assigned> MutateAsync(DGraphSample.Api.Mutation request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Mutate, null, options, request);
      }
      public virtual DGraphSample.Api.Payload Alter(DGraphSample.Api.Operation request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Alter(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual DGraphSample.Api.Payload Alter(DGraphSample.Api.Operation request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Alter, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<DGraphSample.Api.Payload> AlterAsync(DGraphSample.Api.Operation request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AlterAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<DGraphSample.Api.Payload> AlterAsync(DGraphSample.Api.Operation request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Alter, null, options, request);
      }
      public virtual DGraphSample.Api.TxnContext CommitOrAbort(DGraphSample.Api.TxnContext request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CommitOrAbort(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual DGraphSample.Api.TxnContext CommitOrAbort(DGraphSample.Api.TxnContext request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CommitOrAbort, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<DGraphSample.Api.TxnContext> CommitOrAbortAsync(DGraphSample.Api.TxnContext request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CommitOrAbortAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<DGraphSample.Api.TxnContext> CommitOrAbortAsync(DGraphSample.Api.TxnContext request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CommitOrAbort, null, options, request);
      }
      public virtual DGraphSample.Api.Version CheckVersion(DGraphSample.Api.Check request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CheckVersion(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual DGraphSample.Api.Version CheckVersion(DGraphSample.Api.Check request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CheckVersion, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<DGraphSample.Api.Version> CheckVersionAsync(DGraphSample.Api.Check request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CheckVersionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<DGraphSample.Api.Version> CheckVersionAsync(DGraphSample.Api.Check request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CheckVersion, null, options, request);
      }
    }

  }
}
#endregion
