//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGraphSample.DGraph.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DGraphQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DGraphQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DGraphSample.DGraph.Resources.DGraphQueries", typeof(DGraphQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  airports(func: eq(type, &quot;airport&quot;)) {
        ///    uid
        ///    airport_id
        ///    name
        ///    abbr
        ///    city
        ///    state
        ///    country
        ///  }
        ///}.
        /// </summary>
        public static string GetAllAirports {
            get {
                return ResourceManager.GetString("GetAllAirports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query all($type: string) {
        ///  all(func: eq(type, $type)) {
        ///    _predicate_ 
        ///  }
        ///}.
        /// </summary>
        public static string GetAllByType {
            get {
                return ResourceManager.GetString("GetAllByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  carriers(func: eq(type, &quot;carrier&quot;)) {
        ///    uid
        ///    name
        ///    code
        ///  }
        ///}.
        /// </summary>
        public static string GetAllCarriers {
            get {
                return ResourceManager.GetString("GetAllCarriers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type: string @index(exact) .
        ///flight_number: string @index(exact) .
        ///name: string @index(exact) .
        ///airport_id: string @index(exact) .
        ///abbr: string .
        ///code: string .
        ///description: string .
        ///year: int .
        ///month: int .
        ///day_of_month: int .
        ///day_of_week: int .
        ///flight_date: dateTime .
        ///tail_number: string .
        ///cancellation_code: string .
        ///origin_airport: uid @reverse .
        ///destination_airport: uid @reverse .
        ///distance: float .
        ///carrier: uid @reverse .
        ///city: string @index(exact) .
        ///state: string @index(exact) .
        ///cou [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Schema {
            get {
                return ResourceManager.GetString("Schema", resourceCulture);
            }
        }
    }
}
